import Ionicons from '@expo/vector-icons/Ionicons';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors, radius, spacing } from '../theme/tokens';

const modules = [
  { icon: 'layers-outline', title: 'Répétition espacée', text: 'Les notions difficiles reviennent au bon moment.', color: colors.violet, bg: colors.violetSoft },
  { icon: 'reader-outline', title: 'Cas cliniques', text: 'Choisir l’outil adapté avant de le calculer.', color: colors.blue, bg: colors.blueSoft },
  { icon: 'pulse-outline', title: 'ECG Academy', text: 'Fondamentaux, mesures, rythmes et entraînement.', color: colors.teal, bg: colors.mint },
];
export function LearnScreen() { return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.kicker}>APPRENDRE</Text><Text style={styles.title}>Du calcul au réflexe clinique.</Text><Text style={styles.subtitle}>Une progression conçue pour comprendre, appliquer et mémoriser.</Text><View style={styles.list}>{modules.map((item) => <View key={item.title} style={styles.card}><View style={[styles.icon, { backgroundColor: item.bg }]}><Ionicons name={item.icon as keyof typeof Ionicons.glyphMap} size={25} color={item.color} /></View><View style={styles.body}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardText}>{item.text}</Text><View style={styles.badge}><Text style={styles.badgeText}>Bientôt dans la V1</Text></View></View></View>)}</View></ScrollView>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.canvas }, content: { padding: spacing.lg }, kicker: { color: colors.teal, fontWeight: '900', fontSize: 10, letterSpacing: 1.5 }, title: { marginTop: 8, color: colors.ink, fontSize: 31, lineHeight: 37, fontWeight: '900' }, subtitle: { marginTop: 10, color: colors.muted, fontSize: 15, lineHeight: 21 }, list: { marginTop: 28, gap: 14 }, card: { flexDirection: 'row', gap: 15, padding: 18, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line }, icon: { width: 50, height: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, body: { flex: 1 }, cardTitle: { color: colors.ink, fontSize: 17, fontWeight: '900' }, cardText: { marginTop: 5, color: colors.muted, lineHeight: 19 }, badge: { alignSelf: 'flex-start', marginTop: 12, paddingHorizontal: 9, paddingVertical: 5, backgroundColor: colors.canvas, borderRadius: 8 }, badgeText: { color: colors.muted, fontSize: 10, fontWeight: '800' } });
