import Ionicons from '@expo/vector-icons/Ionicons';
import { LinearGradient } from 'expo-linear-gradient';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors, radius, shadow, spacing } from '../theme/tokens';

const benefits = [
  { icon: 'library-outline', title: 'Catalogue clinique complet', text: 'Scores essentiels, spécialisés et sous-estimés dans une seule bibliothèque.' },
  { icon: 'school-outline', title: 'Comprendre, pas seulement calculer', text: 'Explications, pièges, cas cliniques et quiz liés à chaque outil.' },
  { icon: 'analytics-outline', title: 'Progression intelligente', text: 'Révisions ciblées et mémorisation espacée selon vos difficultés.' },
  { icon: 'cloud-offline-outline', title: 'Disponible partout', text: 'Tout le cœur clinique reste accessible sans connexion.' },
] as const;

export function PremiumScreen({ onBack }: { onBack: () => void }) {
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View style={styles.top}><Pressable onPress={onBack} style={styles.back} accessibilityLabel="Retour"><Ionicons name="arrow-back" size={22} color={colors.ink} /></Pressable><View style={styles.secure}><Ionicons name="shield-checkmark" size={15} color={colors.teal} /><Text style={styles.secureText}>ACHAT SÉCURISÉ</Text></View></View>
    <LinearGradient colors={['#0A756C', '#073D3A']} style={styles.hero}>
      <View style={styles.orb} /><View style={styles.crown}><Ionicons name="diamond" size={23} color="#FFE09A" /></View><Text style={styles.label}>MEDICAL TOOLBOX PREMIUM</Text><Text style={styles.title}>Maîtrisez davantage.{`\n`}Hésitez moins.</Text><Text style={styles.subtitle}>L’outil quotidien qui transforme chaque calcul en apprentissage durable.</Text>
      <View style={styles.proofRow}><Proof value="100 %" label="offline" /><Proof value="0" label="publicité" /><Proof value="1" label="espace clinique" /></View>
    </LinearGradient>
    <Text style={styles.sectionTitle}>Ce que Premium change pour vous</Text>
    <View style={styles.list}>{benefits.map((benefit) => <View key={benefit.title} style={styles.benefit}><View style={styles.benefitIcon}><Ionicons name={benefit.icon} size={21} color={colors.teal} /></View><View style={styles.benefitCopy}><Text style={styles.benefitTitle}>{benefit.title}</Text><Text style={styles.benefitText}>{benefit.text}</Text></View><Ionicons name="checkmark-circle" size={20} color={colors.teal} /></View>)}</View>
    <View style={styles.plan}><View style={styles.planHead}><View><Text style={styles.planEyebrow}>ACCÈS PREMIUM</Text><Text style={styles.planTitle}>Une seule expérience. Tout votre parcours.</Text></View><View style={styles.badge}><Text style={styles.badgeText}>RECOMMANDÉ</Text></View></View><Text style={styles.planText}>Le tarif et le moyen de paiement disponibles dans votre pays seront affichés avant toute confirmation.</Text><Pressable style={styles.cta}><Text style={styles.ctaText}>Découvrir l’offre Premium</Text><Ionicons name="arrow-forward" size={18} color="#FFFFFF" /></Pressable><Text style={styles.reassurance}>Aucun paiement automatique sans votre confirmation.</Text></View>
    <View style={styles.trust}><Ionicons name="heart-outline" size={22} color={colors.teal} /><Text style={styles.trustText}><Text style={styles.trustStrong}>Conçu pour votre confiance.</Text>{`\n`}Sources visibles, données locales et limites cliniques clairement indiquées.</Text></View>
  </ScrollView>;
}

function Proof({ value, label }: { value: string; label: string }) { return <View style={styles.proof}><Text style={styles.proofValue}>{value}</Text><Text style={styles.proofLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.canvas }, content: { padding: spacing.lg, paddingBottom: 45 }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, secure: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10, paddingVertical: 7, borderRadius: radius.pill, backgroundColor: colors.mint }, secureText: { color: colors.tealDark, fontSize: 9, fontWeight: '900', letterSpacing: .7 },
  hero: { marginTop: 22, padding: 25, borderRadius: 30, overflow: 'hidden', ...shadow }, orb: { position: 'absolute', width: 220, height: 220, borderRadius: 110, right: -85, top: -90, backgroundColor: 'rgba(255,255,255,.07)' }, crown: { width: 46, height: 46, borderRadius: 15, backgroundColor: 'rgba(255,224,154,.14)', alignItems: 'center', justifyContent: 'center' }, label: { marginTop: 19, color: '#FFE09A', fontSize: 10, fontWeight: '900', letterSpacing: 1.25 }, title: { marginTop: 8, color: '#FFFFFF', fontSize: 31, lineHeight: 37, fontWeight: '900', letterSpacing: -.8 }, subtitle: { marginTop: 11, color: '#C9E1DD', fontSize: 14, lineHeight: 21 }, proofRow: { marginTop: 23, flexDirection: 'row', borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,.14)', paddingTop: 18 }, proof: { flex: 1 }, proofValue: { color: '#FFFFFF', fontWeight: '900', fontSize: 17 }, proofLabel: { color: '#AACBC5', fontSize: 10, marginTop: 2 },
  sectionTitle: { marginTop: 29, marginBottom: 13, color: colors.ink, fontSize: 19, fontWeight: '900' }, list: { gap: 10 }, benefit: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 15, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line }, benefitIcon: { width: 39, height: 39, borderRadius: 13, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center' }, benefitCopy: { flex: 1 }, benefitTitle: { color: colors.ink, fontSize: 14, fontWeight: '900' }, benefitText: { marginTop: 3, color: colors.muted, fontSize: 11, lineHeight: 16 },
  plan: { marginTop: 25, padding: 20, backgroundColor: colors.surface, borderRadius: radius.lg, borderWidth: 1.5, borderColor: colors.teal }, planHead: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 }, planEyebrow: { color: colors.teal, fontSize: 9, fontWeight: '900', letterSpacing: 1 }, planTitle: { marginTop: 6, maxWidth: 215, color: colors.ink, fontSize: 18, lineHeight: 23, fontWeight: '900' }, badge: { alignSelf: 'flex-start', backgroundColor: '#FFF0C7', paddingHorizontal: 8, paddingVertical: 6, borderRadius: radius.pill }, badgeText: { color: '#8A5907', fontSize: 8, fontWeight: '900' }, planText: { marginTop: 14, color: colors.muted, fontSize: 12, lineHeight: 18 }, cta: { marginTop: 18, minHeight: 52, paddingHorizontal: 18, borderRadius: radius.md, backgroundColor: colors.teal, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 }, ctaText: { color: '#FFFFFF', fontWeight: '900', fontSize: 14 }, reassurance: { marginTop: 10, color: colors.muted, fontSize: 10, textAlign: 'center' }, trust: { marginTop: 20, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.mint, borderRadius: radius.md }, trustText: { flex: 1, color: colors.tealDark, fontSize: 11, lineHeight: 17 }, trustStrong: { fontWeight: '900' },
});
