import Ionicons from '@expo/vector-icons/Ionicons';
import { useMemo, useState } from 'react';
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { calculateAdditiveScore, CalculatorValues, getCalculatorDefinition, getDefaultValues } from '../domain/clinical/definitions';
import { ClinicalTool } from '../domain/clinical/types';
import { useActivity } from '../state/ActivityContext';
import { colors, radius, spacing } from '../theme/tokens';

type ScoreChoiceProps = { title: string; shortLabel: string; value: number; options: { value: number; label: string }[]; onChange: (value: number) => void };
function ScoreChoice({ title, shortLabel, value, options, onChange }: ScoreChoiceProps) {
  return <View style={styles.choiceBlock}><Text style={styles.choiceTitle}>{title} ({shortLabel})</Text><View style={styles.options}>{options.map((option) => <Pressable key={option.value} onPress={() => onChange(option.value)} style={[styles.option, value === option.value && styles.optionActive]}><View style={[styles.scoreDot, value === option.value && styles.scoreDotActive]}><Text style={[styles.scoreNumber, value === option.value && styles.scoreNumberActive]}>{option.value}</Text></View><Text style={[styles.optionText, value === option.value && styles.optionTextActive]}>{option.label}</Text>{value === option.value && <Ionicons name="checkmark-circle" size={20} color={colors.teal} />}</Pressable>)}</View></View>;
}

export function ToolScreen({ tool, onBack }: { tool: ClinicalTool; onBack: () => void }) {
  const { isFavorite, toggleFavorite } = useActivity();
  const definition = getCalculatorDefinition(tool.id);
  const [values, setValues] = useState<CalculatorValues>(() => definition ? getDefaultValues(definition) : {});
  const result = useMemo(() => definition ? calculateAdditiveScore(definition, values) : null, [definition, values]);
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View style={styles.top}><Pressable onPress={onBack} style={styles.back} accessibilityLabel="Retour"><Ionicons name="arrow-back" size={22} color={colors.ink} /></Pressable><View style={styles.topActions}><View style={styles.offline}><Ionicons name="cloud-offline-outline" size={14} color={colors.teal} /><Text style={styles.offlineText}>100 % offline</Text></View><Pressable onPress={() => void toggleFavorite(tool.id)} style={styles.favorite} accessibilityLabel={isFavorite(tool.id) ? 'Retirer des favoris' : 'Ajouter aux favoris'}><Ionicons name={isFavorite(tool.id) ? 'heart' : 'heart-outline'} size={21} color={isFavorite(tool.id) ? colors.danger : colors.muted} /></Pressable></View></View>
    <View style={[styles.toolIcon, { backgroundColor: tool.surfaceColor }]}><Ionicons name={tool.icon as keyof typeof Ionicons.glyphMap} size={29} color={tool.color} /></View><Text style={styles.kicker}>{tool.specialty.toUpperCase()} · RISQUE {tool.risk}</Text><Text style={styles.title}>{tool.name}</Text><Text style={styles.summary}>{tool.summary}</Text>
    {!tool.available || !definition || !result ? <View style={styles.unavailable}><Ionicons name="construct-outline" size={24} color={colors.amber} /><View><Text style={styles.unavailableTitle}>Fiche en validation</Text><Text style={styles.unavailableText}>Le calcul sera activé après revue des sources et tests cliniques.</Text></View></View> : <>
      <View style={styles.resultCard}><Text style={styles.resultLabel}>SCORE ACTUEL</Text><Text style={styles.resultValue}>{result.total}<Text style={styles.resultMax}> / {definition.max}</Text></Text><Text style={styles.notation}>{result.notation}</Text><Text style={styles.resultHint}>Toujours communiquer les composantes avec le total.</Text></View>
      {definition.fields.map((field) => <ScoreChoice key={field.id} title={field.label} shortLabel={field.shortLabel} value={values[field.id]} options={field.options} onChange={(value) => setValues((current) => ({ ...current, [field.id]: value }))} />)}
    </>}
    <Info title="Quand l’utiliser ?" icon="help-circle-outline" items={tool.indications} /><Info title="Limites et vigilance" icon="warning-outline" items={tool.limitations} warning />
    {!!tool.sources.length && <View style={styles.info}><View style={styles.infoTitleRow}><Ionicons name="library-outline" size={19} color={colors.teal} /><Text style={styles.infoTitle}>Source vérifiée</Text></View>{tool.sources.map((source) => <Pressable key={source.url} onPress={() => Linking.openURL(source.url)}><Text style={styles.sourceTitle}>{source.title}</Text><Text style={styles.sourceText}>{source.citation}</Text><Text style={styles.sourceMeta}>Consultée le {source.accessedAt} · Fiche v{tool.version}</Text></Pressable>)}</View>}
    <Text style={styles.disclaimer}>Outil pédagogique et d’aide à la décision. Ne remplace pas l’évaluation clinique ni les protocoles locaux.</Text>
  </ScrollView>;
}

function Info({ title, icon, items, warning = false }: { title: string; icon: keyof typeof Ionicons.glyphMap; items: string[]; warning?: boolean }) {
  if (!items.length) return null;
  return <View style={[styles.info, warning && styles.infoWarning]}><View style={styles.infoTitleRow}><Ionicons name={icon} size={19} color={warning ? colors.amber : colors.teal} /><Text style={styles.infoTitle}>{title}</Text></View>{items.map((item) => <View key={item} style={styles.bulletRow}><View style={[styles.bullet, warning && { backgroundColor: colors.amber }]} /><Text style={styles.infoText}>{item}</Text></View>)}</View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.canvas }, content: { padding: spacing.lg, paddingBottom: 50 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, topActions: { flexDirection: 'row', alignItems: 'center', gap: 8 }, back: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line }, favorite: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line }, offline: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.mint, paddingHorizontal: 10, paddingVertical: 7, borderRadius: radius.pill }, offlineText: { color: colors.tealDark, fontSize: 10, fontWeight: '800' }, toolIcon: { marginTop: 24, width: 58, height: 58, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, kicker: { marginTop: 17, color: colors.teal, fontSize: 10, fontWeight: '900', letterSpacing: 1.1 }, title: { marginTop: 7, color: colors.ink, fontSize: 30, fontWeight: '900', letterSpacing: -0.7 }, summary: { marginTop: 8, color: colors.muted, fontSize: 15, lineHeight: 21 },
  resultCard: { marginTop: 24, alignItems: 'center', padding: 23, borderRadius: radius.lg, backgroundColor: colors.tealDark }, resultLabel: { color: '#BDE6DD', fontSize: 9, fontWeight: '900', letterSpacing: 1.4 }, resultValue: { marginTop: 5, color: '#FFFFFF', fontSize: 48, fontWeight: '900' }, resultMax: { fontSize: 20, color: '#BDE6DD' }, notation: { color: '#FFFFFF', fontSize: 15, fontWeight: '800', letterSpacing: 2 }, resultHint: { marginTop: 12, color: '#CBE2DD', fontSize: 11 },
  choiceBlock: { marginTop: 25 }, choiceTitle: { marginBottom: 10, color: colors.ink, fontSize: 17, fontWeight: '900' }, options: { gap: 8 }, option: { minHeight: 50, paddingHorizontal: 13, borderRadius: radius.sm, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 11 }, optionActive: { borderColor: colors.teal, backgroundColor: '#F1FBF8' }, scoreDot: { width: 29, height: 29, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.canvas }, scoreDotActive: { backgroundColor: colors.teal }, scoreNumber: { color: colors.muted, fontWeight: '900' }, scoreNumberActive: { color: '#FFFFFF' }, optionText: { flex: 1, color: colors.ink, fontSize: 14, fontWeight: '600' }, optionTextActive: { color: colors.tealDark, fontWeight: '800' },
  unavailable: { marginTop: 24, padding: 18, borderRadius: radius.md, backgroundColor: colors.amberSoft, flexDirection: 'row', gap: 13 }, unavailableTitle: { color: colors.ink, fontWeight: '900' }, unavailableText: { maxWidth: 270, marginTop: 3, color: colors.muted, fontSize: 12, lineHeight: 17 }, info: { marginTop: 24, padding: 18, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line }, infoWarning: { backgroundColor: colors.amberSoft, borderColor: '#F1D5A9' }, infoTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 11 }, infoTitle: { color: colors.ink, fontSize: 16, fontWeight: '900' }, bulletRow: { flexDirection: 'row', gap: 9, marginTop: 8 }, bullet: { width: 5, height: 5, borderRadius: 3, marginTop: 7, backgroundColor: colors.teal }, infoText: { flex: 1, color: colors.muted, lineHeight: 19, fontSize: 13 }, sourceTitle: { color: colors.teal, fontWeight: '800' }, sourceText: { marginTop: 4, color: colors.muted, fontSize: 12, lineHeight: 17 }, sourceMeta: { marginTop: 8, color: colors.muted, fontSize: 10 }, disclaimer: { marginTop: 25, color: colors.muted, fontSize: 10, lineHeight: 15, textAlign: 'center' },
});
